### ISSUE TITLE
Plugin giving a 504 after 60seconds

### ISSUE THREAD

**Issue by apr-1985** [jenkinsci/prometheus-plugin#10]
Hello.
I have installed the prometheus-plugin (1.0.6) on my Jenkins server (Jenkins version 2.7.20.2).
However when I try to hit /prometheus my browser tries for a minute and then gets a 504 The server didn't respond in time.

Any ideas why this maybe happening?

Cheers

**Comment by Starefossen** [comment]
I have the same problem with prometheus-plugin (1.0.6) on Jenkins 2.34.

**Comment by lsjostro** [comment]
Hi,

Need more info. You can try to debug using a fresh installation of jenkins and add your other plugins one by one? might conflict with something else. I not able to reproduce with my setup. 

Cheers.

**Comment by vredda** [comment]
not sure if this is relevant to the issue described, but I experience similar behavior: 

It seems that for first request the plugin takes a REALLY long time to collect statistics. I have 2 different Jenkins instances:
1) one with several jobs and may be a hundred builds - about 5-10 seconds to get first metrics
2) another with 200+ jobs and few thousands builds - about 5 minutes to get first metrics

for case (2) it causes the Jenkins to stop responding HTTP in a couple of minutes, presumably because typical Prometheus polls metrics every 15 seconds, and this quickly takes out all Jenkins threads to serve incoming requests.

since Metrics Plugin serves metrics from /metrics location without any noticeable delays, I presume it is Prometheus Plugin itself that causes such delays.

**Comment by CoolDuke** [comment]
Have the same problem with Jenkins 2.89.4 and 79 configured jobs.
Calling the /prometheus endpoint I get a 504 Timeout error from Nginx. When I call it again afterwards I get a blank page along with the HTTP 200 status.

**Comment by jmcshane** [comment]
This is the behavior I get as well with 25 jobs and a huge history. My resolution at this point was to disable all the extra functionality in the plugin global configuration, then it started being able to resolve.

I'm going to take a look into this now and see what I could do to identify the cause.

**Comment by krakan** [comment]
We have similar issues - when a Jenkins instance has many pipeline builds with many stages each, the parsing of build times takes a long time, eating up all available CPU and thus rendering the machine unreachable. It may be possible to re-write the way the plugin parses stages to figure out build times so it doesn't need to parse as much for every scrape.

Unfortunately, we haven't been able to schedule time to completely debug this though, so in the meantime we have resorted to disabling the plugin on the affected Jenkins instances - which of course is not a good state of things.

**Comment by lsjostro** [comment]
@krakan completely agree. I would also recommend a complete rewrite. Don't know if they have implemented a better API for retrieving that data? two years since I looked at the code. I don't have bandwidth to look at that either. Hopefully someone out there has more time.

**Comment by markyjackson-taulia** [comment]
@krakan I have started to look in to this
