### ISSUE TITLE
Is there a way to disable the "parameters" label in metrics? 

### ISSUE THREAD

**Issue by Rozzii** [jenkinsci/prometheus-plugin#197]
Hi

I have updated the version of the prometheus-plugin from 2.0.7 to 2.0.8. The update has caused a huge expansion in the amount of data presented on the "/prometheus" endpoint of my Jenkins instance. With version 2.0.7 Prometheus scrapes around 400 kilobytes of data from the endpoint but with the 2.0.8 version it goes up to 85 megabytes and this causes the network traffic  between Prometheus and the Jenkins instance to go up to nearly 200 Mbit/s as the scrape period is 4s in my setup.

The reason behind the change is that with version 2.0.8 now all of the build related metrics contain the complete list of build parameters.  I have not changed anything else on the Jenkins instance and the problem is temporarily fixed as i have simply downgraded to version 2.0.7 and blocked the updates for this plugin for now.

My monitoring setup does not require the "parameters" label at all so with version 2.0.8 Jenkins collects a huge amount of useless data.

I have checked the issues and as i understand this feature was added as part of this issue:https://github.com/jenkinsci/prometheus-plugin/issues/64

**My question:** Is there a way to exclude the build parameters from the metrics right now?
If there is no possibility to exclude the parameters from the metrics then would this feature solve my issue in the future?: https://github.com/jenkinsci/prometheus-plugin/issues/125 . I am not sure that this feature would just add the ability to rename the labels or it would also add the ability to selectively generate the labels.

### Steps to reproduce
Install the 2.0.8 version of the plugin and check the "/prometheus" endpoint.

Jenkins version: 2.263.1

### Notify

@markyjackson-taulia

**Comment by dat-timfa** [comment]
This also causes is high CPU I/O Wait times in cases where an external Volume is used that has trouble handling the high Volume Read Ops due to the massive increase in data scraped.

An environment variable flag similar to other options to disable different collectors. E.g. in some cases I wouldn't need almost any of this: https://github.com/jenkinsci/prometheus-plugin/blob/master/src/main/java/org/jenkinsci/plugins/prometheus/JobCollector.java

Whereas other users may find Job specific details useful, I only care about Queue and general Jenkins details. Having the option to omit Job specific scraping would save considerably on the scraping and volume usage.

---

After downgrading to version 2.0.7, my  CPU I/O Wait % and Volume Read Ops issues were resolved - confirming the surplus (subjective for me) of metrics were absent.
