### ISSUE TITLE
Reporting last run time of a job even when it is currently running.

### ISSUE THREAD

**Issue by sfryffdc** [jenkinsci/prometheus-plugin#289]
### Dependencies

None

### Feature Request

Currently while a build is running the last build time is not reported in the scrape. Is there any way round this as for a busy build it means we can lose information.

**Comment by markyjackson-taulia** [comment]
@sfryffdc Prometheus is configured via command-line flags and a configuration file. The default scrap time is `1m` and that resides on the Prometheus side. The global configuration looks like such:

```
global:
  # How frequently to scrape targets by default.
  [ scrape_interval: <duration> | default = 1m ]
```

I feel it is better to adjust on the Prometheus side rather than the Jenkins plugin side because conflicts with regards to timing drift can occur with I feel would compound your concern.
So my suggestion is to use the Prometheus cli to configure a higher scrap interval globally and Prometheus will reload its configuration at runtime.

Hope that helps.

**Comment by sfryffdc** [comment]
@markyjackson-taulia thanks for the quick response. I think I was wrong in my assertion anyway. I think it is somewhere else in my infrastructure that the apparent gap is coming (prometheus->cortex->grafana). I will dig deeper.

**Comment by sfryffdc** [comment]
@markyjackson-taulia thanks for the quick response. Looking again, it isn't the <namespace>_jenkins_builds_duration_milliseconds_summary_sum that is missing it is the stage last times (<namespace>_jenkins_builds_last_stage_duration_milliseconds_summary_sum). It seems that if a build is running the last stage times are missed for that job. Does that make sense?

**Comment by markyjackson-taulia** [comment]
@sfryffdc That does make sense, I still think the scrap duration is the remedy. Without seeing the actual logs, my gut is telling me it is me that the last stage times are missing because it is happening during the scrap window (default 1m). If you increase the scrap time to 30sec, I think the problem will be solved but this is dependant on the overall stage times. I also want to say that decreasing the scrap intervals can have potential system/application impacts but I would at the very least test this theory in a controlled environment.

**Comment by sfryffdc** [comment]
I have a very long build that takes over an hour, I can just curl the prometheus endpoint during a build and see that the last stage times are missing, increasing the frequency won't help this scenario I'm afraid. I'm looking through the source now, to try and establish how this can happen. Happy to help if I can spot something.

**Comment by markyjackson-taulia** [comment]
@sfryffdc I am going to reopen this issue and run some tests on my end. I will not be able to do that until this weekend but I will update here when I do.
Thanks for bringing this to my attn..

**Comment by sfryffdc** [comment]
@markyjackson-taulia thanks, great. I think the issue in the JobCollector is that processRun is only ever called on the very last run even if it is currently building?

**Comment by markyjackson-taulia** [comment]
That is true, and I think I can build out `observeStage` to be a little more robust.

**Comment by sfryffdc** [comment]
Some further clarification of why this is a problem for us. I've looked at my example again, and realise that the main issue for me is when I have multiple overlapping builds on the same branch. This leads to only recording the values for the last build to finish before a quiet period. Builds in the 'shadow' of other builds never get the chance to record their stage times.
