### ISSUE TITLE
Add failure reason to job

### ISSUE THREAD

**Issue by gchoucair-ohbibi** [jenkinsci/prometheus-plugin#655]
### What feature do you want to see added?

When a job fail, I want to expose the reason of that failure (build fail analyzer) and analyze the fail metric by job.

**Comment by Waschndolos** [comment]
So when default_jenkins_builds_last_build_result_ordinal has value == 2 then add the bfa reason as label?

**Comment by Waschndolos** [comment]
Did you see this? https://github.com/jenkinsci/build-failure-analyzer-plugin/pull/176

**Comment by Waschndolos** [comment]
Coming back at this. Since all BFA related metrics come from the build-failure-analyzer-plugin I'd say the best would be to improve the BFA plugin. e.g. through the PR mentioned in the previous post. Implementing it here in the prometheus plugin doesn't seem to be right place, therefore I'll close this request here soon. I'll comment on the PR of the BFA as well as I think it would be a nice improvement.
